server:
  port: 9008
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.25:3306/tensquare_user?charaterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.25.25
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 192.168.25.25

